#define QUICK_TAP_TERM 0

#define USB_SUSPEND_WAKEUP_DELAY 0
#define AUTO_SHIFT_MODIFIERS
#define AUTO_SHIFT_TIMEOUT 150
#define SERIAL_NUMBER "AqJP6/m5Qg43"
#define LAYER_STATE_8BIT

// #define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

#define QUICK_TAP_TERM 0
#define QUICK_TAPPING_TERM 0
